name: first
favicon: null
layout_spectrum: 0.027602131012827158
typography_spectrum: 0.11646541743539274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060103'
    - '#f0f0f0'
    - '#a64804'
    - '#083aa8'
    - '#a78773'
  brandStrength: 0.9913423405960202
  lightness: 0.6605202290229499
  saturation: 0.7245157102588564
  rhythmicContrast: 0.01950852619484067
purpose: []
