name: first
favicon: null
layout_spectrum: 0.92062
typography_spectrum: 0.06789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c2445'
    - '#9cabc8'
    - '#6c76b3'
    - '#d77984'
    - '#f5c0b0'
  brandStrength: 0
  lightness: 1
  saturation: 0.7245157102588564
  rhythmicContrast: 0.75
purpose: []
